### ISSUE TITLE
I cannot create API with /api new

### ISSUE THREAD

**Issue by GrolonQBilox** [exejar/TabStats#11]
Why?
![1](https://github.com/exejar/TabStats/assets/141205616/e34c13d8-c54c-4cb8-b7e3-5f943162f65c)
Or how to configure my api?

**Comment by exejar** [comment]
Hypixel removed legacy API keys. You can no longer get one with /api new

**Comment by GrolonQBilox** [comment]
> Hypixel 删除了遗留的 API 密钥。你不能再得到一个 /api 新的

Can I configure the api myself?I have my own api.
