### ISSUE TITLE
Replay Mod Compatability

### ISSUE THREAD

**Issue by leafable** [exejar/TabStats#8]
![20220106_173559](https://user-images.githubusercontent.com/90823678/148477180-1d88ca43-0814-4c26-8336-ce95cc98836a.jpg)
Add replay mod compatibility, the tab is bugged in replay mod. Don't mind the evergreenhud and keystrokes btw.

Edit: I also took this photo on my phone because I couldn't find a way to screenshot while pressing tab.

**Comment by Scherso** [comment]
man is running lunar on forge

**Comment by DirectivesMods** [comment]
No
